### ISSUE TITLE
Replace UpdateCheckFrequency key with UpdateCheckInterval in com.microsoft.autoupdate2

### ISSUE THREAD

**Issue by kryptonit1** [ProfileManifests/ProfileManifests#719]
**Name of App / Payload**:
com.microsoft.autoupdate2

**Preference key(s) needing fixing**:
Add `UpdateCheckInterval` and remove `UpdateCheckFrequency`.

**Description of problem(s) / error(s) with listed key(s)**:
UpdateCheckFrequency is [deprecated](https://learn.microsoft.com/en-us/microsoft-365-apps/mac/mau-preferences#updatecheckfrequency) and has been replaced by [UpdateCheckInterval](https://learn.microsoft.com/en-us/microsoft-365-apps/mac/mau-preferences#updatecheckinterval).

**Description of expected behavior**:
N/A

**How are you testing / deploying your profile?**:
N/A

**Comment by kevinmcox** [comment]
Thanks for the issue @kryptonit1. This would be a great one to submit as a first PR if you are interested in giving it a shot.

**Comment by kevinmcox** [comment]
This was fixed in #734.
