### ISSUE TITLE
Add note about 1Password auto-lock setting being manageable via 1Password Admin UI

### ISSUE THREAD

**Issue by apizz** [ProfileManifests/ProfileManifests#727]
### Please provide the following information:

The ask here is just to add a note so that admins know that they can enforce 1Password auto lock now via the main admin management UI across their user base, and are no longer limited to just MDM management for Mac & iOS.  I envision this just as a `pfm_note` with a reference to the 1Password support auto lock policy doc listed below

**Name of App / Payload**: https://github.com/ProfileManifests/ProfileManifests/blob/master/Manifests/ManagedPreferencesApplications/com.1password.1password.plist#L215-L234

**Preference key(s) to be added / updated**: auto-lock ^ linked above

**Applicable Preference Documentation URL(s)**: https://support.1password.com/auto-lock-policy/

**Comment by Fgeronimo** [comment]
I added the note in https://github.com/ProfileManifests/ProfileManifests/pull/736/commits/e2496100794be682307a9a5d09feb72ba969c8c8.
