### ISSUE TITLE
Microsoft AutoUpdate Teams App ID

### ISSUE THREAD

**Issue by Theile** [ProfileManifests/ProfileManifests#731]
### Please provide the following information:

**Name of App / Payload**: com.microsoft.autoupdate2

**Preference key(s) needing fixing**: Microsoft Teams - Application ID

**Description of problem(s) / error(s) with listed key(s)**: Still listed as `TEAMS10` but that is the Classic version.

**Description of expected behavior**: We also need the new version `TEAMS21`

**Applicable Documentation URL(s)**: [MS Application identifiers](https://learn.microsoft.com/en-us/microsoft-365-apps/mac/update-office-for-mac-using-msupdate#application-identifiers)

**How are you testing / deploying your profile?**: It's missing in the pop-up menu.

**Comment by relgit** [comment]
Thanks for reporting this, Søren.

An easy fix we were able to push today. While the PR is pending, you can already use the new value in iMazing Profile Editor.

**Comment by kevinmcox** [comment]
This was fixed in #734.
